package er.routing;

import java.util.List;
import java.util.Map;
import java.util.Objects;

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WOResponse;

import er.extensions.appserver.ERXWOContext;

/**
 * EXPERIMENTAL (route-links branch). A route whose parameters are the components of a record, see docs/ROUTING.md.
 *
 * A route is a constant, and a route declaration gives it its pattern:
 *
 * <pre>
 * public interface Routes {
 *     Route&lt;Search&gt; search = Route.of( Search.class );
 *     PlainRoute about = Route.plain();
 * }
 *
 * ERXRouter.declare( router -&gt; {
 *     router.application().route( "/search/{area}", Routes.search );
 * } );
 * </pre>
 *
 * The record's components are its parameters: those named in the path pattern (the group's prefix included) and in a
 * host pattern, and the rest are query parameters. A page implementing {@code Routes} links to it with
 * {@code <wo:route to="$search" :area="bork" :q="$someString">}, Java code with
 * {@code Routes.search.url( new Search( "bork", someString, null ) )}. The constant stays the same object while the
 * routes are declared again in development, so it's kept anywhere.
 */

public final class Route<P extends Record> extends RouteIdentity<RouteBinding<P>> implements Linkable {

	/**
	 * What the route does when invoked, given its parameters
	 */
	@FunctionalInterface
	public interface Action<P> {
		public WOActionResults invoke( P parameters, RouteInvocation invocation );
	}

	/**
	 * What the route does with bad input, instead of declining the request: a query parameter or field that doesn't
	 * convert, or values the record's constructor refuses (an {@link IllegalArgumentException}, or a
	 * {@link NullPointerException} from {@code Objects.requireNonNull} for a value it requires)
	 */
	@FunctionalInterface
	public interface Invalid {
		public WOActionResults invoke( RouteInvocation invocation, RuntimeException reason );
	}

	private final Class<P> _parametersClass;

	private Route( final Class<P> parametersClass, final Class<?> madeIn ) {
		super( madeIn );
		_parametersClass = Objects.requireNonNull( parametersClass );
	}

	/**
	 * @return A route taking the record, for a constant: a route declaration gives it its pattern, and the application
	 *         doesn't start if none does
	 */
	public static <P extends Record> Route<P> of( final Class<P> parametersClass ) {
		return new Route<>( parametersClass, caller() );
	}

	/**
	 * @return A plain route, for a constant: a route declaration gives it its pattern and what it does, and the
	 *         application doesn't start if none does
	 */
	public static PlainRoute plain() {
		return new PlainRoute( caller() );
	}

	/**
	 * @return A route a declaration makes itself, bound as it's made
	 */
	static <P extends Record> Route<P> unnamed( final Class<P> parametersClass ) {
		return new Route<>( parametersClass, null );
	}

	public Class<P> parametersClass() {
		return _parametersClass;
	}

	/**
	 * @return The whole path pattern, the group's prefix included
	 */
	public String pattern() {
		return binding().pattern();
	}

	/**
	 * @return The names of the route's parameters, in the record's component order
	 */
	public List<String> parameterNames() {
		return binding().parameterNames();
	}

	/**
	 * @return The URL of the route with the given parameters, in the current context
	 */
	public String url( final P parameters ) {
		return url( parameters, ERXWOContext.currentContext() );
	}

	/**
	 * @return The URL of the route with the given parameters, generated by the context the way it generates the
	 *         application's other URLs (short, or with the adaptor prefix). Complete, to the route's host, if the route
	 *         has a host other than the request's.
	 */
	public String url( final P parameters, final WOContext context ) {
		return binding().url( parameters, context );
	}

	/**
	 * @return The route's URL for parameter values by name, as a link or a form has them, without constructing the
	 *         record: only the route parameters must be there (a host parameter can be the request's), so a form's URL
	 *         doesn't depend on its fields. Each value is checked against its component's type.
	 * @throws IllegalArgumentException for a parameter the route doesn't have, a value of the wrong type, or a route
	 *         parameter that's missing
	 */
	@Override
	public String url( final Map<String, Object> values, final WOContext context ) {
		return binding().url( values, context );
	}

	/**
	 * @return The complete URL of the route with the given parameters, without a request (a background job's email): at
	 *         the application's public address ({@link PublicAddress}), which must be set
	 */
	public String completeURL( final P parameters ) {
		return binding().completeURL( parameters );
	}

	@Override
	public String completeURL( final Map<String, Object> values ) {
		return binding().completeURL( values );
	}

	/**
	 * @return A redirect to the route with the given parameters ({@code 303 See Other}), in the current context
	 */
	public WOResponse redirect( final P parameters ) {
		return redirect( parameters, ERXWOContext.currentContext() );
	}

	/**
	 * @return A redirect to the route with the given parameters ({@code 303 See Other}): what a form's post answers with
	 */
	public WOResponse redirect( final P parameters, final WOContext context ) {
		return RouteURLs.seeOther( url( parameters, context ) );
	}

	/**
	 * Has the route answer bad input itself, instead of declining the request: a query parameter or field that doesn't
	 * convert (unless the route takes those with its record, {@link Fields#REPORTED}), or values its record's constructor
	 * refuses. A route parameter that doesn't convert still declines: the URL is wrong, and another route may answer it.
	 * Set in the route's declaration.
	 *
	 * @return The route
	 */
	public Route<P> whenInvalid( final Invalid handler ) {
		binding().whenInvalid( handler );
		return this;
	}

	/**
	 * @return true if fields that don't convert are reported to the route ({@link Fields#REPORTED})
	 */
	boolean reportsFields() {
		return binding().reportsFields();
	}

	@Override
	String description() {
		return "Route.of( %s.class )".formatted( _parametersClass.getSimpleName() );
	}

	@Override
	public String toString() {
		return "Route " + (isBound() || RouteDeclarations.DECLARING.get() != null ? safeBinding() : name());
	}

	private String safeBinding() {
		try {
			return binding().toString();
		}
		catch( IllegalStateException e ) {
			return name();
		}
	}
}
