package er.routing;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;

import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WOResponse;

import er.extensions.appserver.ERXApplication;
import er.extensions.routes.ERXShortURLs;
import er.routing.core.Host;
import er.routing.core.PathPattern;
import er.routing.core.RouteCondition;
import er.routing.core.RouteRequest;

/**
 * EXPERIMENTAL (route-links branch). URLs for route paths, generated by the context the way it generates the
 * application's other URLs: short, or with the adaptor prefix.
 */

public class RouteURLs {

	private RouteURLs() {}

	/**
	 * @return The URL for a route's pattern and host, and parameter values as text: the route's parameters fill the path
	 *         and the host, the others are the query. Complete, to the route's host, if it has one other than the
	 *         request's.
	 */
	static String url( final PathPattern path, final Host host, final Map<String, String> values, final Collection<String> routeParameterNames, final WOContext context ) {
		Objects.requireNonNull( context, "A route URL is generated in a context, and there's none" );

		final String query = values.entrySet().stream()
				.filter( e -> !routeParameterNames.contains( e.getKey() ) )
				.map( e -> URLEncoder.encode( e.getKey(), StandardCharsets.UTF_8 ) + "=" + URLEncoder.encode( e.getValue(), StandardCharsets.UTF_8 ) )
				.collect( Collectors.joining( "&" ) );

		final String url = url( path.path( values ), query.isEmpty() ? null : query, context );

		if( host == null ) {
			return url;
		}

		final String requestHost = context.request() == null ? null : RequestHost.host( context.request() );
		return toRouteHost( url, host.host( values ), requestHost, context.request() != null && context.request().isSecure() );
	}

	/**
	 * @return The URL for a route on the given host: a relative URL stays relative when the request is on that host, and
	 *         is made complete to it otherwise; a complete URL (in a context generating them, an email) always gets the
	 *         route's host, since the context's is the machine's
	 */
	static String toRouteHost( final String url, final String hostName, final String requestHost, final boolean secure ) {
		final boolean complete = url.contains( "://" );

		if( !complete && requestHost != null && new RouteRequest( "GET", requestHost, "/" ).host().equals( hostName ) ) {
			return url;
		}

		return toHost( url, hostName, requestHost, secure );
	}

	/**
	 * @return A {@code 303 See Other} to the URL
	 */
	static WOResponse seeOther( final String url ) {
		final WOResponse response = new WOResponse();
		response.setStatus( 303 );
		response.setHeader( url, "location" );
		return response;
	}

	/**
	 * @param url A URL as the context generated it: relative ({@code /books/2}), or complete in a context generating
	 *        complete URLs (an email)
	 * @param requestHost The request's host as it sent it (possibly with a port), null if there's none
	 * @return The URL to the given host: a complete URL's host replaced, keeping its scheme and port, or a relative URL
	 *         made complete with the request's scheme and port
	 */
	static String toHost( final String url, final String hostName, final String requestHost, final boolean secure ) {
		final int schemeEnd = url.indexOf( "://" );

		if( schemeEnd != -1 ) {
			final int authorityStart = schemeEnd + 3;
			final int pathStart = url.indexOf( '/', authorityStart ) == -1 ? url.length() : url.indexOf( '/', authorityStart );
			return url.substring( 0, authorityStart ) + hostName + port( url.substring( authorityStart, pathStart ) ) + url.substring( pathStart );
		}

		// FIXME: Assumes the request's scheme and port, which a host behind another front end may not share
		return (secure ? "https" : "http") + "://" + hostName + (requestHost == null ? "" : port( requestHost )) + url;
	}

	/**
	 * @return The values, with the host parameters they don't have taken from the request's host, if it matches the
	 *         host pattern: a link within a host doesn't repeat its parameters
	 */
	static Map<String, Object> withHostParameters( final Host host, final Map<String, Object> values, final WOContext context ) {

		if( host == null || host.parameterNames().isEmpty() || context == null || context.request() == null || values.keySet().containsAll( host.parameterNames() ) ) {
			return values;
		}

		final String requestHost = RequestHost.host( context.request() );

		if( requestHost == null || !(host.test( new RouteRequest( "GET", requestHost, "/" ) ) instanceof RouteCondition.Satisfied satisfied) ) {
			return values;
		}

		final Map<String, Object> all = new LinkedHashMap<>( values );
		satisfied.parameters().forEach( ( name, text ) -> all.putIfAbsent( name, new InheritedText( text ) ) );
		return all;
	}

	/**
	 * @return The port of a host as written in a URL or a Host header ({@code :1300}), empty for none
	 */
	private static String port( final String hostAndPort ) {
		final int colon = hostAndPort.lastIndexOf( ':' );
		return colon == -1 || hostAndPort.endsWith( "]" ) ? "" : hostAndPort.substring( colon );
	}

	/**
	 * @param path The route path, encoded ({@code /search/bork})
	 * @param query The query string, encoded, null for none
	 */
	public static String url( final String path, final String query, final WOContext context ) {
		Objects.requireNonNull( context, "A route URL is generated in a context, and there's none" );
		return withoutRouteKey( context.urlWithRequestHandlerKey( ERXShortURLs.ROUTE_KEY, path.substring( 1 ), query ) );
	}

	/**
	 * Routes travel under the route request handler key, which a short URL leaves out ({@code /route/search/bork} is
	 * {@code /search/bork}). FIXME: Belongs in ERXShortURLs, as the reverse of canonicalize(), when this converges
	 */
	private static String withoutRouteKey( final String url ) {

		if( !ERXApplication.erxApplication().shortURLs() ) {
			return url;
		}

		final int schemeEnd = url.indexOf( "://" );
		final int pathStart = schemeEnd == -1 ? 0 : url.indexOf( '/', schemeEnd + 3 );
		final String routePrefix = "/" + ERXShortURLs.ROUTE_KEY;

		if( pathStart == -1 || !url.startsWith( routePrefix, pathStart ) ) {
			return url;
		}

		final int afterKey = pathStart + routePrefix.length();

		if( afterKey == url.length() || url.charAt( afterKey ) == '?' ) {
			return url.substring( 0, pathStart ) + "/" + url.substring( afterKey );
		}

		return url.charAt( afterKey ) == '/' ? url.substring( 0, pathStart ) + url.substring( afterKey ) : url;
	}
}
