# ERRouting's elements (EXPERIMENTAL, route-links branch)

# <wo:route> -> a link to a route (er.routing.components.ERXRouteHyperlink)
route = ERXRouteHyperlink

# <wo:routeForm> -> a form posting to a route (er.routing.components.ERXRouteForm)
routeForm = ERXRouteForm
