cfBundleID=er.erlogginglogback
cfBundleShortVersion=
cfBundleVersion=
classes.dir=bin
component.inlineBindingPrefix=$
component.inlineBindingSuffix=
component.wellFormedTemplateRequired=false
customInfoPListContent=
eoAdaptorClassName=
project.name=ERLoggingLogback
project.name.lowercase=erlogginglogback
project.principal.class=
principalClass=
project.type=framework