package er.extensions.routing;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;

import com.webobjects.appserver.WOApplication;
import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WORequest;
import com.webobjects.appserver.WOResponse;

import er.extensions.foundation.ERXProperties;
import er.extensions.routes.ERXRoutingApplication;
import er.extensions.routes.ERXShortURLs;
import er.routing.matching.PathPattern;
import er.routing.options.Host;
import er.routing.options.RouteCondition;
import er.routing.options.RouteRequest;

/**
 * URLs for route paths, generated by the context the way it generates the
 * application's other URLs: short, or with the adaptor prefix.
 */

final class RouteURLs {

	private RouteURLs() {}

	/**
	 * Refuses a path value with a %, \ or control character, rather than encode it: for a front end or adaptor that
	 * refuses those in a path, encoded
	 */
	static final String STRICT_PATH_VALUES_PROPERTY = "er.routing.strictPathValues";

	/**
	 * The property's value, read once (the configuration is composed before the application starts)
	 */
	private static Boolean _strictPathValues;

	private static boolean strictPathValues() {
		if( _strictPathValues == null ) {
			_strictPathValues = ERXProperties.booleanForKeyWithDefault( STRICT_PATH_VALUES_PROPERTY, false );
		}

		return _strictPathValues;
	}

	/**
	 * @return The URL for a route's pattern and host, and parameter values as text: the route's parameters fill the path
	 *         and the host, the others are the query. Complete, to the route's host, if it has one other than the
	 *         request's.
	 */
	static String url( final PathPattern path, final Host host, final Map<String, String> values, final List<Map.Entry<String, String>> queryValues, final WOContext context ) {

		// Outside a request (a background job), the application's own URL form: a route on a host is a complete URL
		if( context == null ) {
			return host == null ? withoutRequest( path, values, queryValues ) : completeURL( path, host, values, queryValues );
		}

		final String query = query( queryValues );
		final String url = url( path.path( values, strictPathValues() ), query.isEmpty() ? null : query, context );
		final PublicAddress.Origin publicAddress = PublicAddress.configured();

		if( host == null ) {

			// A complete URL (an email's) has the public address, not the machine's name
			return publicAddress != null && url.contains( "://" ) ? publicAddress.origin() + pathAndQuery( url ) : url;
		}

		final String requestHost = context.request() == null ? null : RequestHost.host( context.request() );
		return toRouteHost( url, host.host( values ), requestHost, context.request() != null && context.request().isSecure(), publicAddress );
	}

	/**
	 * @return The complete URL for a route and parameter values as text, without a request: from the application's public
	 *         address (which must be set), in the application's URL form (short, or with the adaptor prefix)
	 */
	static String completeURL( final PathPattern path, final Host host, final Map<String, String> values, final List<Map.Entry<String, String>> queryValues ) {
		final ERXRoutingApplication application = application();
		return completeURL( path, host, values, queryValues, PublicAddress.required(), application.shortURLs() ? null : application.applicationURLPrefix(), application.basePath(), strictPathValues() );
	}

	/**
	 * @return The URL for a route without a host, outside a request: its path in the application's URL form (short, with
	 *         the base path, or with the adaptor prefix), as a link within the application has it
	 */
	private static String withoutRequest( final PathPattern path, final Map<String, String> values, final List<Map.Entry<String, String>> queryValues ) {
		final ERXRoutingApplication application = application();
		final String query = query( queryValues );
		final String routePath = path.path( values, strictPathValues() );
		final String applicationPath = application.shortURLs() ? application.basePath() + routePath : application.applicationURLPrefix() + "/" + ERXShortURLs.ROUTE_KEY + routePath;
		return applicationPath + (query.isEmpty() ? "" : "?" + query);
	}

	/**
	 * @param applicationURLPrefix The application's URL prefix ({@code /cgi-bin/WebObjects/App.woa}), null for short URLs
	 * @param basePath The public path the application is served beneath (short URLs), empty for none
	 */
	static String completeURL( final PathPattern path, final Host host, final Map<String, String> values, final List<Map.Entry<String, String>> queryValues, final PublicAddress.Origin publicAddress, final String applicationURLPrefix, final String basePath ) {
		return completeURL( path, host, values, queryValues, publicAddress, applicationURLPrefix, basePath, false );
	}

	/**
	 * @param strict true to refuse path values some servers refuse, rather than encode them ({@link PathPattern#path(Map, boolean)})
	 */
	static String completeURL( final PathPattern path, final Host host, final Map<String, String> values, final List<Map.Entry<String, String>> queryValues, final PublicAddress.Origin publicAddress, final String applicationURLPrefix, final String basePath, final boolean strict ) {
		final String query = query( queryValues );
		final String routePath = path.path( values, strict );
		final String applicationPath = applicationURLPrefix == null ? basePath + routePath : applicationURLPrefix + "/" + ERXShortURLs.ROUTE_KEY + routePath;
		final String origin = host == null ? publicAddress.origin() : publicAddress.origin( host.host( values ) );
		return origin + applicationPath + (query.isEmpty() ? "" : "?" + query);
	}

	/**
	 * @return The query string for the name and value pairs, in their order (a name repeated for each of a list's values),
	 *         encoded, empty for none
	 */
	private static String query( final List<Map.Entry<String, String>> queryValues ) {
		if( queryValues.isEmpty() ) {
			return "";
		}

		return queryValues.stream()
				.map( e -> URLEncoder.encode( e.getKey(), StandardCharsets.UTF_8 ) + "=" + URLEncoder.encode( e.getValue(), StandardCharsets.UTF_8 ) )
				.collect( Collectors.joining( "&" ) );
	}

	/**
	 * @return The path and query of a URL, without its scheme and host if it has them
	 */
	private static String pathAndQuery( final String url ) {
		final int schemeEnd = url.indexOf( "://" );

		if( schemeEnd == -1 ) {
			return url;
		}

		final int pathStart = url.indexOf( '/', schemeEnd + 3 );
		return pathStart == -1 ? "/" : url.substring( pathStart );
	}

	/**
	 * @return The URL for a route on the given host: a relative URL stays relative when the request is on that host, and
	 *         is made complete to it otherwise; a complete URL (in a context generating them, an email) always gets the
	 *         route's host, since the context's is the machine's
	 */
	static String toRouteHost( final String url, final String hostName, final String requestHost, final boolean secure ) {
		return toRouteHost( url, hostName, requestHost, secure, null );
	}

	static String toRouteHost( final String url, final String hostName, final String requestHost, final boolean secure, final PublicAddress.Origin publicAddress ) {
		final boolean complete = url.contains( "://" );

		if( !complete && requestHost != null && new RouteRequest( "GET", requestHost, "/" ).host().equals( hostName ) ) {
			return url;
		}

		return toHost( url, hostName, requestHost, secure, publicAddress );
	}

	static String toHost( final String url, final String hostName, final String requestHost, final boolean secure ) {
		return toHost( url, hostName, requestHost, secure, null );
	}

	/**
	 * @param url A URL as the context generated it: relative ({@code /books/2}), or complete in a context generating
	 *        complete URLs (an email)
	 * @param requestHost The request's host as it sent it (possibly with a port), null if there's none
	 * @param publicAddress The application's public address, whose scheme and port the URL gets, null for none
	 * @return The URL to the given host: with the public address's scheme and port if there is one, otherwise a complete
	 *         URL's own (its host replaced), or the request's for a relative URL
	 */
	static String toHost( final String url, final String hostName, final String requestHost, final boolean secure, final PublicAddress.Origin publicAddress ) {

		if( publicAddress != null ) {
			return publicAddress.origin( hostName ) + pathAndQuery( url );
		}

		final int schemeEnd = url.indexOf( "://" );

		if( schemeEnd != -1 ) {
			final int authorityStart = schemeEnd + 3;
			final int pathStart = url.indexOf( '/', authorityStart ) == -1 ? url.length() : url.indexOf( '/', authorityStart );
			return url.substring( 0, authorityStart ) + hostName + port( url.substring( authorityStart, pathStart ) ) + url.substring( pathStart );
		}

		// Without a public address, the request's scheme and port
		return (secure ? "https" : "http") + "://" + hostName + (requestHost == null ? "" : port( requestHost )) + url;
	}

	/**
	 * @return A {@code 303 See Other} to the URL
	 */
	static WOResponse seeOther( final String url ) {
		final WOResponse response = new WOResponse();
		response.setStatus( 303 );
		response.setHeader( url, "location" );
		return response;
	}

	/**
	 * @return The values, with the host parameters they don't have taken from the request's host, if it matches the
	 *         host pattern: a link within a host doesn't repeat its parameters
	 */
	static Map<String, Object> withHostParameters( final Host host, final Map<String, Object> values, final WOContext context ) {
		return withHostParameters( host, values, context == null ? null : context.request() );
	}

	static Map<String, Object> withHostParameters( final Host host, final Map<String, Object> values, final WORequest request ) {

		if( host == null || host.parameterNames().isEmpty() || request == null || values.keySet().containsAll( host.parameterNames() ) ) {
			return values;
		}

		final String requestHost = RequestHost.host( request );

		if( requestHost == null || !(host.test( new RouteRequest( "GET", requestHost, "/" ) ) instanceof RouteCondition.Satisfied satisfied) ) {
			return values;
		}

		final Map<String, Object> all = new LinkedHashMap<>( values );
		satisfied.parameters().forEach( ( name, text ) -> all.putIfAbsent( name, new InheritedText( text ) ) );
		return all;
	}

	/**
	 * @return The port of a host as written in a URL or a Host header ({@code :1300}), empty for none
	 */
	private static String port( final String hostAndPort ) {
		final int colon = hostAndPort.lastIndexOf( ':' );
		return colon == -1 || hostAndPort.endsWith( "]" ) ? "" : hostAndPort.substring( colon );
	}

	/**
	 * @param path The route path, encoded ({@code /search/bork})
	 * @param query The query string, encoded, null for none
	 */
	public static String url( final String path, final String query, final WOContext context ) {
		Objects.requireNonNull( context, "A route URL is generated in a context, and there's none" );
		final ERXRoutingApplication application = application();

		// The usual link, relative with short URLs, is the path beneath the base path: what composing it under the route
		// key and shortening it gives, without composing it (a page may have thousands)
		if( application.shortURLs() && isRelative( context ) ) {
			return application.basePath() + path + (query == null ? "" : "?" + query);
		}

		return withoutRouteKey( context.urlWithRequestHandlerKey( ERXShortURLs.ROUTE_KEY, path.substring( 1 ), query ) );
	}

	/**
	 * @return true if the context composes relative URLs, as WOContext decides: not when it's asked for complete ones, or
	 *         when its secure mode isn't the request's
	 */
	private static boolean isRelative( final WOContext context ) {
		return !context.doesGenerateCompleteURLs() && (context.request() == null || context.secureMode() == context.request().isSecure());
	}

	/**
	 * @return The short URL to a route without the route key it was composed under, see
	 *         {@link ERXShortURLs#withoutRouteKey(String, String)}
	 */
	private static String withoutRouteKey( final String url ) {
		final ERXRoutingApplication application = application();
		return application.shortURLs() ? ERXShortURLs.withoutRouteKey( url, application.basePath() ) : url;
	}


	/**
	 * @return The application, as far as its URLs go (short or long, its base path and prefix)
	 */
	private static ERXRoutingApplication application() {
		return (ERXRoutingApplication)WOApplication.application();
	}

}
