cfBundleID=er.extensions.control
cfBundleShortVersion=
cfBundleVersion=
classes.dir=bin
component.inlineBindingPrefix=$
component.inlineBindingSuffix=
component.wellFormedTemplateRequired=false
customInfoPListContent=
eoAdaptorClassName=
project.name=ERControl
project.name.lowercase=ercontrol
project.principal.class=er.extensions.control.ERXControl
principalClass=er.extensions.control.ERXControl
project.type=framework
