package er.extensions.experimental.routing;

import java.util.Objects;

import com.webobjects.appserver.WOContext;

import er.extensions.appserver.ERXApplication;
import er.extensions.routes.ERXShortURLs;

/**
 * EXPERIMENTAL (route-links branch). URLs for route paths, generated by the context the way it generates the
 * application's other URLs: short, or with the adaptor prefix.
 */

public class RouteURLs {

	private RouteURLs() {}

	/**
	 * @param path The route path, encoded ({@code /search/bork})
	 * @param query The query string, encoded, null for none
	 */
	public static String url( final String path, final String query, final WOContext context ) {
		Objects.requireNonNull( context, "A route URL is generated in a context, and there's none" );
		return withoutRouteKey( context.urlWithRequestHandlerKey( ERXShortURLs.ROUTE_KEY, path.substring( 1 ), query ) );
	}

	/**
	 * Routes travel under the route request handler key, which a short URL leaves out ({@code /route/search/bork} is
	 * {@code /search/bork}). FIXME: Belongs in ERXShortURLs, as the reverse of canonicalize(), when this converges
	 */
	private static String withoutRouteKey( final String url ) {

		if( !ERXApplication.erxApplication().shortURLs() ) {
			return url;
		}

		final int schemeEnd = url.indexOf( "://" );
		final int pathStart = schemeEnd == -1 ? 0 : url.indexOf( '/', schemeEnd + 3 );
		final String routePrefix = "/" + ERXShortURLs.ROUTE_KEY;

		if( pathStart == -1 || !url.startsWith( routePrefix, pathStart ) ) {
			return url;
		}

		final int afterKey = pathStart + routePrefix.length();

		if( afterKey == url.length() || url.charAt( afterKey ) == '?' ) {
			return url.substring( 0, pathStart ) + "/" + url.substring( afterKey );
		}

		return url.charAt( afterKey ) == '/' ? url.substring( 0, pathStart ) + url.substring( afterKey ) : url;
	}
}
