classes.dir=target/classes
component.inlineBindingPrefix=$
component.inlineBindingSuffix=
component.wellFormedTemplateRequired=false
customInfoPListContent=
eoAdaptorClassName=
principalClass=ajaxplayground.Application
project.name=AjaxPlayground
project.name.lowercase=ajaxplayground
project.type=application
webXML=false
webXML_CustomContent=
project.base=wo
